 # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: whatee
  version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
  summary: A Unofficial WhatsApp desktop client # 79 char long summary
  description: A simple unofficial WhatsApp desktop client.
  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots
  icon: assets/icons/png/128x128.png
  apps:
    whatee:
      command: whatee
      plugs:
        - network
        - desktop

  parts:
    whatee:
      source: .
      # See 'snapcraft plugins'
      plugin: nil